id: test_metric
description: Test Metric Definition
fun_expr: test_data/average_temperature
stages:
- execution_type: python
  output_type: 0
  lvl: 3
- query: test_metric.sql
  execution_type: store
  output_type: 1
  lvl: 3
w_time: 300
fun_vars:
- location
- average_temperature